# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gergely strommer / stromi
email: stromi@stromi.net
description: > # this means to ignore newlines until "baseurl:"
  graphic, web & UI designer with a passion for coding (mainly frontend, of coourse) modern web development tools, endless SCSS and JS filechains, come whatever may...
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://stromi.net/" # the base hostname & protocol for your site
twitter_username: gergelystrommer
github_username:  stromi

# Build settings
markdown: kramdown

# sass:
#   style: compressed


# gems:
  # - octopress-autoprefixer

exclude: ["_src",       
          "_plugins",
          "gulpfile.js",
          "node_modules",
          "package.json"]

collections:
  works:
    output: true
    permalink: work/:path/


asset_bundler:
compress:
  js: true
  css: false
base_path: /
server_url:
remove_bundled: false
dev: false
bundle_name: false
markup_templates:
  js: "<script type='text/javascript' src='{{url}}'></script>\n"
  